#!/usr/bin/env bash
#
# setup_project.sh — Bootstrap the qMEMO research project
#
# Falcon-512 Post-Quantum Signature Benchmarking for Blockchain Applications
#
# This script is idempotent: running it multiple times will not overwrite
# existing files or corrupt previous results.  It only creates directories
# and files that do not already exist, and always refreshes system specs.
#
# Usage:
#   chmod +x setup_project.sh
#   ./setup_project.sh

set -euo pipefail

# ── Colours (disabled when stdout is not a terminal) ────────────────────────
if [ -t 1 ]; then
    BOLD='\033[1m'
    GREEN='\033[0;32m'
    CYAN='\033[0;36m'
    YELLOW='\033[0;33m'
    RED='\033[0;31m'
    RESET='\033[0m'
else
    BOLD='' GREEN='' CYAN='' YELLOW='' RED='' RESET=''
fi

PROJECT_ROOT="$(cd "$(dirname "$0")" && pwd)"

# ── Helpers ─────────────────────────────────────────────────────────────────
info()  { printf "${CYAN}[INFO]${RESET}  %s\n" "$*"; }
ok()    { printf "${GREEN}[ OK ]${RESET}  %s\n" "$*"; }
warn()  { printf "${YELLOW}[WARN]${RESET}  %s\n" "$*"; }
fail()  { printf "${RED}[FAIL]${RESET}  %s\n" "$*" >&2; exit 1; }

# Create a directory only if it doesn't exist yet.
ensure_dir() {
    if [ -d "$1" ]; then
        ok "Directory exists: $1"
    else
        mkdir -p "$1"
        ok "Created directory: $1"
    fi
}

# Write a file only if it doesn't exist yet. Content comes from stdin.
write_if_missing() {
    local dest="$1"
    if [ -f "$dest" ]; then
        ok "File exists (skipped): $dest"
    else
        cat > "$dest"
        ok "Created file: $dest"
    fi
}

# ── 1. System requirements ──────────────────────────────────────────────────
printf "\n${BOLD}═══════════════════════════════════════════════════════════════${RESET}\n"
printf "${BOLD}  qMEMO — Falcon-512 Benchmark Project Setup${RESET}\n"
printf "${BOLD}═══════════════════════════════════════════════════════════════${RESET}\n\n"

info "Checking system requirements …"

OS="$(uname -s)"
case "$OS" in
    Darwin) OS_PRETTY="macOS $(sw_vers -productVersion 2>/dev/null || echo 'unknown')" ;;
    Linux)  OS_PRETTY="Linux $(uname -r)" ;;
    *)      fail "Unsupported OS: $OS (macOS or Linux required)" ;;
esac
ok "Operating system: $OS_PRETTY"

ARCH="$(uname -m)"
ok "Architecture: $ARCH"

# ── 2. Detect hardware specs ────────────────────────────────────────────────
info "Detecting hardware specifications …"

if [ "$OS" = "Darwin" ]; then
    CPU_MODEL="$(sysctl -n machdep.cpu.brand_string 2>/dev/null || echo 'unknown')"
    CPU_CORES="$(sysctl -n hw.ncpu 2>/dev/null || echo 'unknown')"
    RAM_BYTES="$(sysctl -n hw.memsize 2>/dev/null || echo 0)"
    RAM_GB="$(( RAM_BYTES / 1073741824 )) GB"
else
    CPU_MODEL="$(grep -m1 'model name' /proc/cpuinfo 2>/dev/null | cut -d: -f2 | xargs || echo 'unknown')"
    CPU_CORES="$(nproc 2>/dev/null || grep -c ^processor /proc/cpuinfo 2>/dev/null || echo 'unknown')"
    RAM_KB="$(grep MemTotal /proc/meminfo 2>/dev/null | awk '{print $2}' || echo 0)"
    RAM_GB="$(( RAM_KB / 1048576 )) GB"
fi

TIMESTAMP="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
HOSTNAME_STR="$(hostname 2>/dev/null || echo 'unknown')"

printf "\n"
printf "  ${BOLD}CPU Model :${RESET} %s\n" "$CPU_MODEL"
printf "  ${BOLD}CPU Cores :${RESET} %s\n" "$CPU_CORES"
printf "  ${BOLD}RAM       :${RESET} %s\n" "$RAM_GB"
printf "  ${BOLD}OS        :${RESET} %s\n" "$OS_PRETTY"
printf "  ${BOLD}Arch      :${RESET} %s\n" "$ARCH"
printf "  ${BOLD}Hostname  :${RESET} %s\n" "$HOSTNAME_STR"
printf "  ${BOLD}Timestamp :${RESET} %s\n" "$TIMESTAMP"
printf "\n"

# ── 3. Directory structure ──────────────────────────────────────────────────
info "Setting up directory structure …"

ensure_dir "$PROJECT_ROOT/benchmarks/src"
ensure_dir "$PROJECT_ROOT/benchmarks/bin"
ensure_dir "$PROJECT_ROOT/benchmarks/results"
ensure_dir "$PROJECT_ROOT/benchmarks/data"
ensure_dir "$PROJECT_ROOT/docs"
ensure_dir "$PROJECT_ROOT/scripts"

# ── 4. System specs document (always refreshed) ────────────────────────────
info "Writing system specifications to docs/SYSTEM_SPECS.md …"

cat > "$PROJECT_ROOT/docs/SYSTEM_SPECS.md" <<SPECS
# System Specifications

> Auto-generated by \`setup_project.sh\` — ${TIMESTAMP}

| Property  | Value |
|-----------|-------|
| CPU Model | ${CPU_MODEL} |
| CPU Cores | ${CPU_CORES} |
| RAM       | ${RAM_GB} |
| OS        | ${OS_PRETTY} |
| Arch      | ${ARCH} |
| Hostname  | ${HOSTNAME_STR} |

## Notes

- Re-run \`./setup_project.sh\` to refresh these specs on a different machine.
- Benchmark results in \`benchmarks/results/\` record per-run hardware info as JSON metadata.
SPECS
ok "Wrote docs/SYSTEM_SPECS.md"

# ── 5. Project README ──────────────────────────────────────────────────────
info "Creating README templates …"

write_if_missing "$PROJECT_ROOT/README.md" <<'README'
# qMEMO — Falcon-512 Post-Quantum Signature Benchmarks

## Overview

This project benchmarks **Falcon-512** (a NIST-selected post-quantum digital signature scheme) in the context of blockchain transaction signing and verification. The goal is to quantify latency, throughput, and resource consumption to evaluate practical deployment readiness.

## Repository Layout

```
├── benchmarks/
│   ├── src/        # C source code for benchmark harnesses
│   ├── bin/        # Compiled binaries (git-ignored)
│   ├── results/    # Timestamped JSON benchmark outputs
│   └── data/       # Raw measurement data
├── docs/           # Documentation & system specs
├── scripts/        # Automation & helper scripts
└── setup_project.sh
```

## Getting Started

```bash
chmod +x setup_project.sh
./setup_project.sh
```

## Methodology

1. **Key Generation** — Measure wall-clock and CPU time for Falcon-512 keypair generation.
2. **Signing** — Benchmark transaction signing over payloads of varying size.
3. **Verification** — Benchmark signature verification under single and batch modes.
4. **Comparison** — Compare against classical ECDSA (secp256k1) baselines.

## Hardware

See [docs/SYSTEM_SPECS.md](docs/SYSTEM_SPECS.md) for the machine profile used in each run.

## References

- [Falcon — Fast-Fourier Lattice-based Compact Signatures over NTRU](https://falcon-sign.info/)
- [NIST Post-Quantum Cryptography Standardization](https://csrc.nist.gov/projects/post-quantum-cryptography)

## License

TBD
README

write_if_missing "$PROJECT_ROOT/benchmarks/README.md" <<'README'
# Benchmarks

## Source (`src/`)

C source files implementing the benchmark harnesses for Falcon-512 operations:
key generation, signing, and verification.

## Binaries (`bin/`)

Compiled executables — not tracked in version control.

## Results (`results/`)

Timestamped JSON files capturing benchmark outcomes. Each file includes:
- Hardware metadata
- Parameter configuration
- Raw timing measurements
- Summary statistics (mean, median, std-dev, p95, p99)

## Data (`data/`)

Raw measurement data and intermediate artifacts used during analysis.
README

write_if_missing "$PROJECT_ROOT/docs/README.md" <<'README'
# Documentation

This directory contains:

- **SYSTEM_SPECS.md** — Auto-detected hardware profile of the benchmarking machine.
- Additional methodology notes, analysis write-ups, and figures.
README

write_if_missing "$PROJECT_ROOT/scripts/README.md" <<'README'
# Scripts

Automation and utility scripts for the qMEMO benchmark suite.

## Planned Scripts

| Script | Purpose |
|--------|---------|
| `run_benchmarks.sh` | Execute the full benchmark suite |
| `collect_results.sh` | Aggregate JSON results into summary tables |
| `plot_results.py` | Generate comparison charts from result data |
README

# ── 6. .gitignore ───────────────────────────────────────────────────────────
info "Setting up .gitignore …"

write_if_missing "$PROJECT_ROOT/.gitignore" <<'GITIGNORE'
# ── Compiled / binary ───────────────────────────────────────────────────────
benchmarks/bin/
*.o
*.so
*.dylib
*.a
*.out

# ── Data & results (large / machine-specific; keep in cloud storage) ────────
# Uncomment the next two lines if you prefer NOT to track results in git:
# benchmarks/results/
# benchmarks/data/

# ── OS / editor ─────────────────────────────────────────────────────────────
.DS_Store
Thumbs.db
*.swp
*.swo
*~
.vscode/
.idea/

# ── Python (analysis notebooks / scripts) ──────────────────────────────────
__pycache__/
*.pyc
.venv/
venv/
*.egg-info/

# ── Secrets / credentials ──────────────────────────────────────────────────
.env
*.pem
*.key
GITIGNORE

# ── 7. Placeholder source file ─────────────────────────────────────────────
write_if_missing "$PROJECT_ROOT/benchmarks/src/.gitkeep" <<< ""
write_if_missing "$PROJECT_ROOT/benchmarks/data/.gitkeep" <<< ""
write_if_missing "$PROJECT_ROOT/benchmarks/results/.gitkeep" <<< ""

# ── Done ────────────────────────────────────────────────────────────────────
printf "\n${BOLD}${GREEN}Setup complete.${RESET}\n"
printf "Project root: ${BOLD}%s${RESET}\n\n" "$PROJECT_ROOT"
printf "Next steps:\n"
printf "  1. cd %s\n" "$PROJECT_ROOT"
printf "  2. git init && git add -A && git commit -m 'Initial project scaffold'\n"
printf "  3. Add Falcon-512 reference implementation to benchmarks/src/\n"
printf "  4. Write benchmark harnesses and run them\n\n"
